import type { FriendLink } from "../types/config";

export const projectsPageConfig = {
	columns: 3,
};

export const projectsConfig: FriendLink[] = [
	{
		title: "团子的邮箱",
		imgurl: "https://re.tsh520.cn/zl/tx.webp",
		desc: "个人使用的邮箱服",
		siteurl: "https://email.0824.uk/inbox",
		tags: ["我的网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "团子的相册",
		imgurl: "https://re.tsh520.cn/zl/tx.webp",
		desc: "个人照片存储与展示",
		siteurl: "https://ph.tsh520.cn/",
		tags: ["我的网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "团子和蛋糕的博客",
		imgurl: "https://re.tsh520.cn/zl/tx.webp",
		desc: "个人技术与生活分享博客",
		siteurl: "https://blog.tsh520.cn/",
		tags: ["我的网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "Emoji词典",
		imgurl: "https://www.emojiall.com/favicon.ico",
		desc: "全面的emoji表情查询工具",
		siteurl: "https://www.emojiall.com/",
		tags: ["资源网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "樱之空动漫",
		imgurl: "https://skr.skr3.cc:666/favicon.ico",
		desc: "动漫资源分享平台",
		siteurl: "https://skr.skr3.cc:666/user/plays.html",
		tags: ["资源网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "100%多功能图片转换器",
		imgurl: "https://imagestool.com/favicon.ico",
		desc: "在线图片格式转换工具",
		siteurl: "https://imagestool.com/webp2jpg-online/",
		tags: ["资源网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "Fomalhaut🥝",
		imgurl: "https://www.fomal.cc/favicon.ico",
		desc: "技术博主个人网站",
		siteurl: "https://www.fomal.cc/",
		tags: ["大佬博客收藏"],
		weight: 8,
		enabled: true,
	},
	{
		title: "海拥",
		imgurl: "https://blog.haiyong.site/favicon.ico",
		desc: "前端技术分享博客",
		siteurl: "https://blog.haiyong.site/",
		tags: ["大佬博客收藏"],
		weight: 8,
		enabled: true,
	},
	{
		title: "喵斯基部落",
		imgurl: "https://blog.moewah.com/favicon.ico",
		desc: "运维技术与经验分享",
		siteurl: "https://blog.moewah.com/",
		tags: ["大佬博客收藏"],
		weight: 8,
		enabled: true,
	},
	{
		title: "Cloudflare",
		imgurl: "https://dash.cloudflare.com/favicon.ico",
		desc: "全球CDN与网络安全服务",
		siteurl:
			"https://dash.cloudflare.com/2668bf8cf06b94446afeb47b8b23496f/home/domains",
		tags: ["常用网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "在线本地字体预览",
		imgurl: "https://www.lddgo.net/favicon.ico",
		desc: "本地字体在线预览工具",
		siteurl: "https://www.lddgo.net/convert/local-font-preview",
		tags: ["工具网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "在线ping",
		imgurl: "https://www.itdog.cn/favicon.ico",
		desc: "多线路网络延迟测试工具",
		siteurl: "https://www.itdog.cn/",
		tags: ["工具网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "免费在线抠图",
		imgurl: "https://www.koukoutu.com/favicon.ico",
		desc: "无需上传的在线图像抠图工具",
		siteurl: "https://www.koukoutu.com/removebgtool/all",
		tags: ["工具网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "Free Font 艺术体",
		imgurl: "https://font.ittools.cc/favicon.ico",
		desc: "商用免费字体收集",
		siteurl: "https://font.ittools.cc/art",
		tags: ["工具网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "释放字体自由",
		imgurl: "https://fonts.zeoseven.com/favicon.ico",
		desc: "字体资源分享网站",
		siteurl: "https://fonts.zeoseven.com/",
		tags: ["工具网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "Maps | MapTiler Cloud",
		imgurl: "https://cloud.maptiler.com/favicon.ico",
		desc: "地图服务与可视化平台",
		siteurl: "https://cloud.maptiler.com/maps/",
		tags: ["其他网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "Qwerty Learner",
		imgurl: "https://qwerty.kaiyi.cool/favicon.ico",
		desc: "键盘工作者单词记忆软件",
		siteurl: "https://qwerty.kaiyi.cool/gallery",
		tags: ["学习网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "面试鸭",
		imgurl: "https://www.mianshiya.com/favicon.ico",
		desc: "程序员面试题库平台",
		siteurl: "https://www.mianshiya.com/",
		tags: ["学习网站"],
		weight: 8,
		enabled: true,
	},
	{
		title: "Firefly Docs",
		imgurl: "https://docs-firefly.cuteleaf.cn/favicon.ico",
		desc: "Firefly项目文档",
		siteurl: "https://docs-firefly.cuteleaf.cn/zh/",
		tags: ["文档"],
		weight: 8,
		enabled: true,
	},
];

export const getEnabledProjects = (): FriendLink[] => {
	return projectsConfig
		.filter((project) => project.enabled)
		.sort((a, b) => b.weight - a.weight);
};
